openapi: 3.1.0
info:
  version: 1.0.0
  title: My water App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a document of my water app.
tags:
  - name: Water
    description: Operations about water.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
paths:
  /water/{id}:
    get:
      $ref: ../swagger/paths/water/{id}/get.yaml
    patch:
      $ref: '../swagger/paths/water/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/water/{id}/delete.yaml'
  /water:
    get:
      $ref: '../swagger/paths/water/get.yaml'
    post:
      $ref: '../docs/swagger/paths/water/post.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
